import os

import numpy as np
from numpy.typing import NDArray

class LammpsData:
    def __str__(self): ...

def read(filename: str | os.PathLike[str]) -> LammpsData: ...
def write(filename: str | os.PathLike[str], lammps_data: LammpsData) -> None: ...
def get_xyz_regions(lammps_data: LammpsData) -> NDArray[np.float64]: ...
def get_atom_poses(lammps_data: LammpsData) -> NDArray[np.float64]: ...
def get_atom_velocities(lammps_data: LammpsData) -> NDArray[np.float64]: ...
def get_atom_poses_dict(lammps_data: LammpsData) -> dict[int, NDArray[np.float64]]: ...
def get_atom_velocities_dict(
    lammps_data: LammpsData,
) -> dict[int, NDArray[np.float64]]: ...
def update_atom_poses(
    lammps_data: LammpsData,
    poses_dict: dict[int, NDArray[np.float64]],
) -> None: ...
def update_atom_velocities(
    lammps_data: LammpsData,
    velocities_dict: dict[int, NDArray[np.float64]],
) -> None: ...
